ENCRYPTIONS_OBJECTS=SymAlg.o      \
                    AES.o         \
                    Blowfish.o    \
                    Camellia.o    \
                    CAST128.o     \
                    CAST256.o     \
                    DES.o         \
                    DESX.o        \
                    GOST.o        \
                    IDEA.o        \
                    MISTY1.o      \
                    RC2.o         \
                    RC4.o         \
                    RC5.o         \
                    RC6.o         \
                    RC_PQ.o       \
                    SAFERK64.o    \
                    SEED.o        \
                    Skipjack.o    \
                    TDES.o        \
                    TEA.o         \
                    Twofish.o     \
                    XTEA.o